services:
  wordpress:
    build: 
      context: ./requirements/wordpress
    image: wordpress
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      WP_URL: ${WP_URL}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_GENERAL_USER: ${WP_GENERAL_USER}
      WP_GENERAL_PASSWORD: ${WP_GENERAL_PASSWORD}
      WP_GENERAL_EMAIL: ${WP_GENERAL_EMAIL}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wp_network

  mariadb:
    build: 
      context: ./requirements/mariadb
    image: mariadb
    environment:
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp_network

  nginx:
    build: 
      context: ./requirements/nginx
      image: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wp_network

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/dy/data/wordpress
      o: bind
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/dy/data/mariadb
      o: bind

networks:
  wp_network:
